name: Continuous Integration

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node_version: 14.x

      - id: vars
        shell: bash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - run: npm ci

      - name: Run Unit Tests
        run: npm run test

      - name: Run Linting
        run: npm run lint

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: mohamedf0
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and Publish
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: quay.io/mohamedf0/sample-app:${{ steps.vars.outputs.sha_short }},quay.io/mohamedf0/sample-app:latest
